### ISSUE TITLE
Update notification 

### ISSUE THREAD

**Issue by kevinsnijder** [HELLBOY017/Project-Zephyrus_Releases#1]
I got an update notification to update to android 13. Is this safe to do? The updater actually allows me to install the update.
![Screenshot_20230130-211622](https://user-images.githubusercontent.com/22765565/215585647-70086a38-454f-46e1-a61d-568ba34a019b.png)

**Comment by HELLBOY017** [comment]
No don't do it.
Also it's sad to tell that the support has been dropped for our aosp variants.

We'll comeback soon with a CodeLinaro based variant.
You can check the updates on it on our telegram group:-
https://t.me/ZephyrusOP8
